### PR TITLE
Bug fixing

### LINKED ISSUE #629: Bug: On Email Template Pages delete second back button
Delete second back button as there is already one at top of page

Bildschirmfoto 2019-10-10 um 14 02 24

### PR DESCRIPTION
**Pull request by thejoefriel**
fixes #629 #639 #633 #624

### CODE REVIEW

File: v2/client/src/components/pages/survey/index.js [hunk 1]
```diff
@@ -549,7 +535,7 @@ class Survey extends Component {
                       PIN={PIN}
                       PINvalid={PINvalid}
                       handlePIN={this.handlePIN}
-                      onPINBlur={this.checkPINonBlur}
+                      onPINBlur={() => this.checkPINonBlur}
```
Comment (RamyAlshurafa) [inline v2/client/src/components/pages/survey/index.js]: this stops the validation on blur function from working
