### PR TITLE
Simon bugfixes s4

### LINKED ISSUE #567: Bug: Newly added trainer clicks "I don't want my trainer manager/ local lead to view my feedback data" in email and nothing happens
https://www.loom.com/share/b4a810d35b11415cbd4f33f3be180f77

- clicking link in email directs to error page -> best to direct to page saying 'your request was successful. We've removed you from the trainer group."
- trainer is still in group -> should be getting removed
relates #511

### LINKED ISSUE #571: Bug: Cannot add trainer to group if previously deleted from group
app crashes when i want to re-add a trainer to my group.

### PR DESCRIPTION
**Pull request by dupreesi**
should fix #571 #568 #549, #551, #586

- now local leads/ trainer managers should be able to remove and add trainers from their group without issues -> please check

- every manager/ local lead can add trainers to multiple groups (please check flow for both user roles)

- validation so that only managers can be added that are not yet the trainer's manager

- emailing updated, to test  please comment 
```
 // if (process.env.NODE_ENV === 'production') { 
      await addNewTrainerToGroup(emailInfo);
   // }
```
to simulate production mode

### CODE REVIEW

File: v2/server/controllers/users/addTrainerToGroup.js [hunk 1]
```diff
@@ -2,57 +2,61 @@ const boom = require('boom');
...
+    if (trainer && managers.length > 0) {
+      // check for duplicates
+      managers.map(el => {
+        if (trainer.managers.includes(el.key.toString())) {
+          errors.push(el.label);
+        }
+      });
+
+      // run functions
+      Promise.all([
```
Comment (RamyAlshurafa) [inline v2/server/controllers/users/addTrainerToGroup.js]:
```suggestion
      await Promise.all([
```

without `await` it will not wait for these queries to be executed and will move to the next lines directly, and will not catch the errors if occurred in any of these queries

File: v2/server/database/queries/users/localLead/index.js [hunk 2]
```diff
@@ -3,12 +3,40 @@ const User = require('./../../../models/User');
 
 module.exports.getAllLocalLeads = () => User.find({ role: 'localLead' });
 
-module.exports.addTrainertoGroup = (localLeadId, trainerId) => {
```
Comment (RamyAlshurafa) [inline v2/server/database/queries/users/localLead/index.js]: this function name was used in `controllers/users/editProfile.js`
so the edit profile throws an error when you try to change the official local lead in edit profile
Screenshot from 2019-09-24 11-18-12
